trigger:
  branches:
    include:
      - dev
      - master      # production branch của bạn

variables:
  buildConfiguration: 'Release'
  dotnetVersion: '8.0.x'
  azureServiceConnection: 'ServiceConnection_RestAPI_FarmTimeManagement'
  webAppName: 'flindersdevops'
  # hiện không dùng slot
  webAppSlot: 'staging'

pool:
  name: 'SelfHosted_Agent_Tom'

stages:
# ===================== BUILD (chung cho mọi nhánh) =====================
- stage: Build
  displayName: Build & Test & Package
  jobs:
  - job: Build
    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET SDK $(dotnetVersion)'
      inputs:
        packageType: 'sdk'
        version: '$(dotnetVersion)'

    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: 'restore'
        projects: '**/*.sln'

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: 'build'
        projects: '**/*.sln'
        arguments: '--configuration $(buildConfiguration)'
        publishWebProjects: false

    - task: DotNetCoreCLI@2
      displayName: Test
      inputs:
        command: 'test'
        projects: '**/*Tests/*.csproj'
        arguments: '--configuration $(buildConfiguration) --collect "XPlat Code Coverage"'
      continueOnError: true

    - task: DotNetCoreCLI@2
      displayName: Publish (dotnet publish)
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

    - task: ArchiveFiles@2
      displayName: Zip published output
      inputs:
        rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/webapp.zip'

    - publish: '$(Build.ArtifactStagingDirectory)/webapp.zip'
      displayName: 'Publish deploy artifact'
      artifact: 'drop'

# ===================== TẠO ARTIFACT PROJECT-SRC (chỉ khi master) =====================
- stage: Build_Prod_Artifact
  displayName: Build Production Artifact (project-src.zip)
  dependsOn: Build
  condition: >
    and(
      succeeded(),
      or(
        eq(variables['Build.SourceBranch'], 'refs/heads/master'),
        and(
          eq(variables['Build.Reason'], 'PullRequest'),
          eq(variables['System.PullRequest.TargetBranch'], 'refs/heads/master')
        )
      )
    )
  jobs:
  - job: PackageSource
    displayName: 'Package project source'
    steps:
    - powershell: |
        $src = "$(Build.SourcesDirectory)"
        $outDir = "$(Build.ArtifactStagingDirectory)\project-src"
        $zip = "$(Build.ArtifactStagingDirectory)\project-src.zip"

        if (Test-Path $outDir) { Remove-Item $outDir -Recurse -Force }
        New-Item -ItemType Directory -Force -Path $outDir | Out-Null

        # Copy source, loại bỏ các thư mục không cần
        robocopy $src $outDir /E /XD ".git" ".github" ".azuredevops" "node_modules" "bin" "obj" ".vs" ".idea" ".vscode" 1>$null

        if (Test-Path $zip) { Remove-Item $zip -Force }
        Add-Type -AssemblyName 'System.IO.Compression.FileSystem'
        [System.IO.Compression.ZipFile]::CreateFromDirectory($outDir, $zip)
      displayName: 'Create project-src.zip'

    - publish: '$(Build.ArtifactStagingDirectory)/project-src.zip'
      displayName: 'Publish production source artifact'
      artifact: 'project-src'

# ===================== DEPLOY (đổi tên hiển thị, vẫn deploy Production) =====================
- stage: Deploy_Prod
  displayName: Deploy to Development
  dependsOn:
    - Build
  condition: >
    and(
      succeeded(),
      or(
        eq(variables['Build.SourceBranch'], 'refs/heads/master'),
        and(
          eq(variables['Build.Reason'], 'PullRequest'),
          eq(variables['System.PullRequest.TargetBranch'], 'refs/heads/master')
        )
      )
    )
  jobs:
  - deployment: DeployProd
    environment: 'prod'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              artifact: 'drop'
              path: '$(Pipeline.Workspace)/drop'

          # Debug: in biến nhánh (an toàn cả Manual/CI/PR)
          - powershell: |
              $b = $env:BUILD_SOURCEBRANCH
              $r = $env:BUILD_REASON
              $t = $env:SYSTEM_PULLREQUEST_TARGETBRANCH
              if (-not $t) { $t = '<not set>' }

              Write-Host "Build.SourceBranch              = $b"
              Write-Host "Build.Reason                    = $r"
              Write-Host "System.PullRequest.TargetBranch = $t"
              Write-Host "Package path                    = $(Pipeline.Workspace)\drop\webapp.zip"
            displayName: 'Print branch variables'
            failOnStderr: false

          - task: AzureWebApp@1
            displayName: 'Deploy to $(webAppName) (Production slot)'
            inputs:
              azureSubscription: '$(azureServiceConnection)'
              appName: '$(webAppName)'
              package: '$(Pipeline.Workspace)/drop/webapp.zip'
              # Không cấu hình slot -> deploy mặc định vào Production
