trigger:
  - main

pool:
  vmImage: 'windows-latest'   # Bắt buộc Windows nếu dùng MSDeploy/PublishProfile

variables:
  buildConfiguration: 'Release'
  packagePath: '$(Build.ArtifactStagingDirectory)/WebApp.zip'   # MSDeploy package output
  webAppName: 'flindersdevops'

steps:
  # 1) .NET 8 SDK (để restore NuGet, build SDK-style)
  - task: UseDotNet@2
    displayName: 'Use .NET 8 SDK'
    inputs:
      packageType: 'sdk'
      version: '8.x'

  # 2) Restore
  - task: DotNetCoreCLI@2
    displayName: 'Restore'
    inputs:
      command: 'restore'
      projects: '**/*.sln'

  # 3) (Tùy chọn) Test
  - task: DotNetCoreCLI@2
    displayName: 'Test'
    inputs:
      command: 'test'
      projects: '**/*Tests/*.csproj'
      arguments: '--configuration $(buildConfiguration)'
    condition: succeededOrFailed()

  # 4) Đóng gói MSDeploy package bằng MSBuild
  #    => TẠO RA file WebApp.zip theo định dạng Web Deploy (khác zip thường)
  - task: MSBuild@1
    displayName: 'Package Web Deploy (MSDeploy)'
    inputs:
      solution: '**/*.csproj'                # Nếu có nhiều csproj, nên chỉ định đúng Web API csproj
      msbuildArchitecture: 'x64'
      configuration: '$(buildConfiguration)'
      msbuildArguments: >
        /p:DeployOnBuild=true
        /p:WebPublishMethod=Package
        /p:PackageAsSingleFile=true
        /p:SkipInvalidConfigurations=true
        /p:PackageLocation="$(packagePath)"

  # 5) Tải publish profile (đã upload ở Library > Secure files)
  - task: DownloadSecureFile@1
    name: fetchProfile
    displayName: 'Download publish profile'
    inputs:
      secureFile: 'flindersdevops.PublishSettings'   # Đúng tên file bạn đã upload

  # 6) Trích password (userPWD) từ .PublishSettings -> lưu vào biến bí mật
  - powershell: |
      [xml]$xml = Get-Content '$(fetchProfile.secureFilePath)'
      $pwd = $xml.publishData.publishProfile[0].userPWD
      if ([string]::IsNullOrWhiteSpace($pwd)) {
        throw "Không tìm thấy userPWD trong publish profile. Hãy bật Basic Auth và tải profile mới từ Portal."
      }
      Write-Host "##vso[task.setvariable variable=publishProfilePassword;issecret=true]$pwd"
    displayName: 'Extract publish profile password'

  # 7) Deploy bằng Publish Profile (MSDeploy)
  - task: AzureRmWebAppDeployment@5
    displayName: 'Deploy to Azure Web App (Publish Profile + MSDeploy)'
    inputs:
      ConnectionType: 'PublishProfile'
      PublishProfilePath: '$(fetchProfile.secureFilePath)'
      PublishProfilePassword: '$(publishProfilePassword)'
      Package: '$(packagePath)'              # PHẢI là MSDeploy package .zip ở bước 4
      # DeploymentType: 'webDeploy'          # Mặc định là webDeploy khi dùng PublishProfile
