trigger:
  branches:
    include:
      - dev
      - main

variables:
  buildConfiguration: 'Release'
  dotnetVersion: '8.0.x'
  azureServiceConnection: 'ServiceConnection_RestAPI_FarmTimeManagement'
  webAppName: 'flindersdevops'
  webAppSlot: 'staging'   # hiện chưa dùng slot, nhưng giữ lại nếu sau này cần

pool:
  name: 'SelfHosted_Agent_Tom'

stages:
- stage: Build
  displayName: Build & Test & Package
  jobs:
  - job: Build
    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET SDK $(dotnetVersion)'
      inputs:
        packageType: 'sdk'
        version: '$(dotnetVersion)'

    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: 'restore'
        projects: '**/*.sln'

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: 'build'
        projects: '**/*.sln'
        arguments: '--configuration $(buildConfiguration)'
        publishWebProjects: false

    - task: DotNetCoreCLI@2
      displayName: Test
      inputs:
        command: 'test'
        projects: '**/*Tests/*.csproj'
        arguments: '--configuration $(buildConfiguration) --collect "XPlat Code Coverage"'
      continueOnError: true

    - task: DotNetCoreCLI@2
      displayName: Publish (dotnet publish)
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

    - task: ArchiveFiles@2
      displayName: Zip published output
      inputs:
        rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/webapp.zip'

    - publish: '$(Build.ArtifactStagingDirectory)/webapp.zip'
      displayName: 'Publish artifact'
      artifact: 'drop'

# ===================== DEPLOY PRODUCTION =====================
- stage: Deploy_Prod
  displayName: Deploy to Production (main branch)
  dependsOn: Build
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs:
  - deployment: DeployProd
    environment: 'prod'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              artifact: 'drop'
              path: '$(Pipeline.Workspace)/drop'

          # Block debug in ra biến
          - powershell: |
              Write-Host "Build.SourceBranch              = $(Build.SourceBranch)"
              Write-Host "Build.Reason                    = $(Build.Reason)"
              Write-Host "System.PullRequest.TargetBranch = $(System.PullRequest.TargetBranch)"
              Write-Host "Package path                    = $(Pipeline.Workspace)\drop\webapp.zip"
            displayName: 'Print branch variables'

          - task: AzureWebApp@1
            displayName: 'Deploy to $(webAppName) - production'
            inputs:
              azureSubscription: '$(azureServiceConnection)'
              appName: '$(webAppName)'
              package: '$(Pipeline.Workspace)/drop/webapp.zip'
