trigger:
  - main

pool:
  vmImage: 'windows-latest'   # cần Windows cho MSDeploy

variables:
  buildConfiguration: 'Release'
  projectPath: '**/*.csproj'                          # SỬA: trỏ đúng Web API .csproj
  packagePath: '$(Build.ArtifactStagingDirectory)/WebApp.zip'

steps:
  # 1) .NET 8 SDK
  - task: UseDotNet@2
    displayName: 'Use .NET 8 SDK'
    inputs:
      packageType: 'sdk'
      version: '8.x'

  # 2) Restore
  - task: DotNetCoreCLI@2
    displayName: 'Restore'
    inputs:
      command: 'restore'
      projects: '$(projectPath)'

  # 3) Đóng gói MSDeploy package (bắt buộc khi dùng Publish Profile)
  - task: MSBuild@1
    displayName: 'Package Web Deploy (MSDeploy)'
    inputs:
      solution: '$(projectPath)'          # Nên chỉ định đúng csproj Web API
      msbuildArchitecture: 'x64'
      configuration: '$(buildConfiguration)'
      msbuildArguments: >
        /p:DeployOnBuild=true
        /p:WebPublishMethod=Package
        /p:PackageAsSingleFile=true
        /p:SkipInvalidConfigurations=true
        /p:PackageLocation="$(packagePath)"

  # 4) Tải publish profile từ Secure files
  - task: DownloadSecureFile@1
    name: fetchProfile
    displayName: 'Download publish profile'
    inputs:
      secureFile: 'flindersdevops.PublishSettings'   # đúng tên đã upload

  # 5) TẠO FILE PUBLISH PROFILE CHỈ CHỨA MSDEPLOY + LẤY PASSWORD
  - powershell: |
      [xml]$xml = Get-Content '$(fetchProfile.secureFilePath)'

      # Tìm profile có publishMethod="MSDeploy"
      $ms = $xml.publishData.publishProfile | Where-Object { $_.publishMethod -eq 'MSDeploy' } | Select-Object -First 1
      if (-not $ms) { throw "Không tìm thấy publishProfile có publishMethod='MSDeploy' trong .PublishSettings." }

      # Lưu password vào biến bí mật
      $pwd = $ms.userPWD
      if ([string]::IsNullOrWhiteSpace($pwd)) { throw "MSDeploy profile không có userPWD. Hãy bật Basic Auth và tải lại profile." }
      Write-Host "##vso[task.setvariable variable=publishProfilePassword;issecret=true]$pwd"

      # Xuất ra file PublishSettings chỉ chứa đúng MSDeploy profile
      $new = New-Object System.Xml.XmlDocument
      $decl = $new.CreateXmlDeclaration("1.0","utf-8",$null)
      $new.AppendChild($decl) | Out-Null
      $root = $new.CreateElement("publishData")
      $new.AppendChild($root) | Out-Null
      $imported = $new.ImportNode($ms, $true)
      $root.AppendChild($imported) | Out-Null

      $outPath = "$(Build.SourcesDirectory)\msdeploy.PublishSettings"
      $new.Save($outPath)
      Write-Host "##vso[task.setvariable variable=msdeployProfilePath]$outPath"
    displayName: 'Filter MSDeploy profile & extract password'

  # 6) Deploy bằng Publish Profile (webDeploy)
  - task: AzureRmWebAppDeployment@5
    displayName: 'Deploy to Azure App Service (Publish Profile + MSDeploy)'
    inputs:
      ConnectionType: 'PublishProfile'
      PublishProfilePath: '$(msdeployProfilePath)'
      PublishProfilePassword: '$(publishProfilePassword)'
      Package: '$(packagePath)'
      # webDeploy là mặc định khi ConnectionType=PublishProfile
