# azure-pipelines.yml
trigger:
  branches:
    include:
      - dev
      - main

variables:
  buildConfiguration: 'Release'
  dotnetVersion: '8.0.x'
  # Giữ nguyên các biến môi trường hiện có
  azureServiceConnection: 'ServiceConnection_RestAPI_FarmTimeManagement'
  webAppName: 'flindersdevops'
  # webAppSlot vẫn giữ lại nếu bạn muốn dùng sau này, nhưng hiện tại KHÔNG dùng
  webAppSlot: 'staging'

pool:
  name: 'SelfHosted_Agent_Tom'

stages:
# ===================== BUILD =====================
- stage: Build
  displayName: Build & Test & Package
  jobs:
  - job: Build
    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET SDK $(dotnetVersion)'
      inputs:
        packageType: 'sdk'
        version: '$(dotnetVersion)'

    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: 'restore'
        projects: '**/*.sln'

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: 'build'
        projects: '**/*.sln'
        arguments: '--configuration $(buildConfiguration)'
        publishWebProjects: false

    - task: DotNetCoreCLI@2
      displayName: Test
      inputs:
