trigger:
  - main

pool:
  vmImage: 'windows-latest'   # cần Windows cho MSDeploy/PublishProfile

variables:
  buildConfiguration: 'Release'
  # ĐƯỜNG DẪN TỚI WEB API CSPROJ CHÍNH — NHỚ SỬA CHO ĐÚNG!
  projectPath: '**/*.csproj'
  # File MSDeploy package output (khác zip thường)
  packagePath: '$(Build.ArtifactStagingDirectory)/WebApp.zip'

steps:
  # 1) .NET 8 SDK
  - task: UseDotNet@2
    displayName: 'Use .NET 8 SDK'
    inputs:
      packageType: 'sdk'
      version: '8.x'

  # 2) Restore
  - task: DotNetCoreCLI@2
    displayName: 'Restore'
    inputs:
      command: 'restore'
      projects: '$(projectPath)'

  # 3) ĐÓNG GÓI MSDEPLOY PACKAGE (bắt buộc khi dùng Publish Profile)
  - task: MSBuild@1
    displayName: 'Package Web Deploy (MSDeploy)'
    inputs:
      solution: '$(projectPath)'          # nên trỏ đúng tới Web API .csproj chính
      msbuildArchitecture: 'x64'
      configuration: '$(buildConfiguration)'
      msbuildArguments: >
        /p:DeployOnBuild=true
        /p:WebPublishMethod=Package
        /p:PackageAsSingleFile=true
        /p:SkipInvalidConfigurations=true
        /p:PackageLocation="$(packagePath)"

  # 4) Tải publish profile đã upload trong Library > Secure files
  - task: DownloadSecureFile@1
    name: fetchProfile
    displayName: 'Download publish profile'
    inputs:
      secureFile: 'flindersdevops.PublishSettings'   # đúng tên file bạn đã upload

  # 5) Trích password (userPWD) từ PublishSettings -> lưu vào biến bí mật
  - powershell: |
      [xml]$xml = Get-Content '$(fetchProfile.secureFilePath)'
      $pwd = $xml.publishData.publishProfile[0].userPWD
      if ([string]::IsNullOrWhiteSpace($pwd)) {
        throw "Không tìm thấy userPWD trong publish profile. Hãy bật Basic Auth và tải profile mới."
      }
      Write-Host "##vso[task.setvariable variable=publishProfilePassword;issecret=true]$pwd"
    displayName: 'Extract publish profile password'

  # 6) Deploy bằng Publish Profile (webDeploy)
  - task: AzureRmWebAppDeployment@5
    displayName: 'Deploy to Azure App Service (Publish Profile)'
    inputs:
      ConnectionType: 'PublishProfile'
      PublishProfilePath: '$(fetchProfile.secureFilePath)'
      PublishProfilePassword: '$(publishProfilePassword)'
      Package: '$(packagePath)'
