trigger:
  - main

pool:
  vmImage: 'windows-latest'   # Microsoft-hosted (Windows để dùng msdeploy/zip deploy)

variables:
  buildConfiguration: 'Release'
  publishDir: '$(Build.ArtifactStagingDirectory)/webapp'
  packagePath: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
  webAppName: 'flindersdevops'

steps:
  - task: UseDotNet@2
    displayName: 'Use .NET 8 SDK'
    inputs:
      packageType: 'sdk'
      version: '8.x'

  - task: DotNetCoreCLI@2
    displayName: 'Restore'
    inputs:
      command: 'restore'
      projects: '**/*.sln'

  - task: DotNetCoreCLI@2
    displayName: 'Build'
    inputs:
      command: 'build'
      projects: '**/*.sln'
      arguments: '--configuration $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: 'Test'
    inputs:
      command: 'test'
      projects: '**/*Tests/*.csproj'
      arguments: '--configuration $(buildConfiguration)'
    condition: succeededOrFailed()

  - task: DotNetCoreCLI@2
    displayName: 'Publish'
    inputs:
      command: 'publish'
      publishWebProjects: true
      arguments: '--configuration $(buildConfiguration) --output $(publishDir)'
      zipAfterPublish: false

  - task: ArchiveFiles@2
    displayName: 'Zip published app'
    inputs:
      rootFolderOrFile: '$(publishDir)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(packagePath)'
      replaceExistingArchive: true

  # Tải publish profile (đã upload ở Library > Secure files)
  - task: DownloadSecureFile@1
    name: fetchProfile
    displayName: 'Download publish profile'
    inputs:
      secureFile: 'flindersdevops.PublishSettings'   # đúng tên file bạn đã upload

  # Trích password (userPWD) từ file .PublishSettings và lưu vào biến bí mật
  - powershell: |
      [xml]$xml = Get-Content '$(fetchProfile.secureFilePath)'
      # Nhiều khi có nhiều <publishProfile>, lấy cái đầu tiên
      $pwd = $xml.publishData.publishProfile[0].userPWD
      if ([string]::IsNullOrWhiteSpace($pwd)) {
        throw "Không tìm thấy userPWD trong publish profile. Hãy kiểm tra đã bật Basic Auth và tải profile mới."
      }
      Write-Host "##vso[task.setvariable variable=publishProfilePassword;issecret=true]$pwd"
    displayName: 'Extract publish profile password'

  # Deploy bằng Publish Profile (v5 yêu cầu cả Path + Password)
  - task: AzureRmWebAppDeployment@5
    displayName: 'Deploy to Azure Web App (Publish Profile)'
    inputs:
      ConnectionType: 'PublishProfile'
      PublishProfilePath: '$(fetchProfile.secureFilePath)'
      PublishProfilePassword: '$(publishProfilePassword)'
      Package: '$(packagePath)'
      #DeploymentType: 'zipDeploy'   # có thể bật nếu muốn ép Zip Deploy
